### ISSUE TITLE
TOT: /dashboard/(data) and layout 기획에 대한 이야기

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#131]
## 📝 개요
- 데이터 테이블
![image](https://github.com/user-attachments/assets/330c38d2-dd9b-4243-8ccf-dc7f4c05193d)
  - 행을 선택하면 상세보기로 들어가짐
  - 현재는 체크박스를 누르기 너무 불편해요!
    1. 체크박스 크기를 엄청 크게
    2. 왼쪽영역에서의 click이벤트를 없애고 왼쪽영역 클릭시 체크박스 change
    3. 세션접속 버튼 col을 만듬(이게 직관적이지 않나? 아무리 호버링시 커서가 포인터가되고 row ui가 바뀐다해도)
- 스위치
  * 역할 변경을 스위치 ui로 하는건 나도 애매하다 생각(굳이 안될건 없지만...)
  * 그래서 뭘로하지? 참고할 ui가 필요
  * 대쉬보드->드라이브에는 단순히 내가 호스트일때 올린 파일들이 나옴 (참가자인데 드라이브 들어가면 안헷갈리려나?)
  * 기본적으로 역할 변경을 통해 영향받는 기능은
    1. 사이드바 유틸리티 버튼(세션 접속 or 세션 참가)
    2. 세션 테이블(내가 호스트인 세션 or 내가 참가자인 세션)

## 👀 ETC
- 참고할 기존 서비스 ui가 있을까요?

**Comment by easyandones** [comment]
1. 데이터 테이블
- 세션 접속 버튼을 각 행마다 추가하기 => 문제 없음. Good. 오히려 빠르게 접근 가능하고 직관적임

각 행마다 넣으면 안된다고 생각하는 것
- 클릭 미스로 인한 결과가 치명적인 경우
- 한번에 여러개를 처리할 수 있어야하는 기능의 경우
ex) 삭제 버튼

각 행마다 넣으면 좋다고 생각하는 것
- 한번에 하나씩만 처리하는 기능의 경우 (한번에 하나씩만 사용하는 기능의 경우)
- 자주 사용되는 기능의 경우 (접근성이 좋아야 함)
ex) 세션 접속 버튼


세션 접속 버튼을 행마다 추가하는 것은 문제 없음
하지만 결국 삭제 작업이나 다른 작업들의 편의성을 위해 체크박스는 필요할 것 같음
체크박스를 조금 더 크게 만들고 동시에 체크박스 주변 영역은 사각형으로 분리해서 hover, click 이벤트가 모두 체크박스로 가도록 하는게 좋을듯
a랑 b를 모두 적용하는 방식



2. 그냥 스위치 말고 버튼으로 하는 것도 괜찮을듯
- 현재 계정 상태를 표시하는 부분 바로 위나 밑에 [~~~ 모드로 전환] 이런 버튼을 크게 두면 괜찮을듯

가독성이나 직관성 이런거 나중에 개선 적용해야겠지만 일단 대충 느낌만 내본다면 이런 느낌이 되지 않을까 싶음


<img width="287" alt="image" src="https://github.com/user-attachments/assets/487721c0-62af-42cc-8161-171b3f18115c">

**Comment by 1000chw** [comment]
1. 세션 접속 버튼을 각 행에 추가하는게 좋아 보임.

이렇게 됐을 때, 우리가 세션에서 파일을 봐야 하는 구조니까, 파일 보는 버튼도 있어야 되고, 삭제 버튼도 있어야 함.
그러면 각각의 행에 메뉴버튼을 넣고 그 안에 버튼 3개를 다 넣는게 UI적으로 더 낫지 않나? 싶은 생각도 들긴 함.

2. role이 host <-> participant 바뀔 때 변화하는게 세션 리스트랑 세션 참가|생성인데
 - 이 경우에 차라리 세션참가, 생성 버튼 둘 다 좌측 메뉴바? 에 넣고
 - 세션 리스트 안에 스위치나 버튼을 넣어서 세션 리스트 안에서만 바뀌는게 나을 수도 있지 않을까?
