### ISSUE TITLE
TOT: 사이드바 기획 변경

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#154]
## 📝 개요
- 사이드바 기획 변경에 대한 논의
![image](https://github.com/user-attachments/assets/dd194355-6dc6-4e95-941b-57958e8e0a32)
- 현재 기능을 구조화해보면 사이드바에 
  1. 설정
  2. 내파일
  3. 세션참가 
  4. 내가 참가자인 세션
  5. 세션생성
  6. 내가 호스트인 세션
- 이것들을 다 넣는 것이 더 직관적이고 굳이 역할 버튼(스위치)를 바꿀 필요 없이 더 편하다고 생각
  - 충분히 공간이 돼서, subTitle이나 Divider로 구분만해도 가능하다 생각
  - 왜냐하면 역할별로 나뉘는 기능이 2개밖에 없음, 매우 적다고 생각 -> 역할 버튼(스위치)로 나누는 것에 대한 필요성 감소
  - 코드적으로도 더 깔끔하게 작성할 수 있단 생각
- 내 설정 버튼을 누르면, 로그아웃과 내 정보 수정을 한번에 띄워주는 페이지나 모달이나 팝오버가 나오는 것이 적절하다 생각
  - 우리 서비스는 유저 설정에 대해 할 것이 따로 없음 (default displayName 하나 정도?)
## ✔️ To-Do
- [ ] 의견 작성

## 👀 ETC
1. 논의할게 아니다, 나중에 하거나 누군가에게 위임하고 그것에 따르자
2. 지금이 ~~하므로 지금을 유지해야한다
3. 바꾸면 ~~에 대한 이득이 있으므로 바꾸자

**Comment by easyandones** [comment]
괜찮은듯

**Comment by nayounsang** [comment]
> 괜찮은듯

@easyandones 
바꾸는게 좋다??

**Comment by easyandones** [comment]
> > 괜찮은듯
> 
> @easyandones 바꾸는게 좋다??

스위치 방식 보다는 더 좋은듯

**Comment by easyandones** [comment]
closed by #173
