### ISSUE TITLE
FE: modal 컴포넌트 라우팅 문제

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#274]
## 📝 개요
- modal 창이 열린 상태에서 이전/다음 페이지 등 페이지 이동이 발생하여도 modal 창이 그대로 남아있는 문제

**Comment by nayounsang** [comment]
페이지 이동이 언제 동작할 수 있는거지? 강제로 유저가 뒤로가기버튼등을 눌러 history stack이 변화될떄?

**Comment by easyandones** [comment]
> 페이지 이동이 언제 동작할 수 있는거지? 강제로 유저가 뒤로가기버튼등을 눌러 history stack이 변화될떄?

맞음

**Comment by nayounsang** [comment]
> > 페이지 이동이 언제 동작할 수 있는거지? 강제로 유저가 뒤로가기버튼등을 눌러 history stack이 변화될떄?
> 
> 맞음

Overlay toolkit써 아니면 state써? 전자면 rootLayout에 의존성배열이 path,queryParams인 useEffect하나 넣으면 돼서

**Comment by easyandones** [comment]
> > > 페이지 이동이 언제 동작할 수 있는거지? 강제로 유저가 뒤로가기버튼등을 눌러 history stack이 변화될떄?
> > 
> > 
> > 맞음
> 
> Overlay toolkit써 아니면 state써? 전자면 rootLayout에 의존성배열이 path,queryParams인 useEffect하나 넣으면 돼서

useEffect로 이미 해결했음
ModalContainer 자체 문제라 모든 modal에 영향 주던 버그임
