### ISSUE TITLE
FE: 파일 뷰어 구현

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#276]
## 📝 개요
- /viewer/[fileID] 경로에 파일 뷰어 구현

**Comment by nayounsang** [comment]
이미 라우트 있는거 아니야? 파일 미리보기말하는건지 아니면 세션장을 말하는건지?

**Comment by easyandones** [comment]
> 이미 라우트 있는거 아니야? 파일 미리보기말하는건지 아니면 세션장을 말하는건지?

세션 말고 드라이브에서 파일만 보는 뷰어

**Comment by nayounsang** [comment]
이미 이름이 비슷한 view라는 라우트가 있는데 이걸 바꾸거나 아니면 files하위디렉토리에 넣는게 좋아보여

**Comment by easyandones** [comment]
> 이미 view라는 라우트가 있는데 이걸 바꾸거나 아니면 files하위디렉토리에 넣는게 좋아보여

파일만 보는 뷰어라 sidebar가 없는게 더 좋아서 따로 디렉토리 바꿨음.
view라는 라우트 이름을 더 어울리게 바꾸는게 좋을듯

**Comment by nayounsang** [comment]
그리고 우리 오늘은 https://github.com/tldraw/tldraw-yjs-example 분석하기로해서 필기기능을 위해 공부하는것도 좋아보여 
꼭 필요한 기능같아보여도 디테일한 것이라면 잠시 멈추고 우리 핵심기능 일정 파악을 위해 사이클 돌리는게 좋을 것 같아

**Comment by easyandones** [comment]
> > 이미 view라는 라우트가 있는데 이걸 바꾸거나 아니면 files하위디렉토리에 넣는게 좋아보여
> 
> 파일만 보는 뷰어라 sidebar가 없는게 더 좋아서 따로 디렉토리 바꿨음. view라는 라우트 이름을 더 어울리게 바꾸는게 좋을듯

https://session.catchup.tools/<:sessionID>
https://catchup.tools/s/<:sessionID>

**Comment by nayounsang** [comment]
후자에 s대신 어떤 단어를 넣는게 더 유저입장에서 편할 것 같아
아니면 기존 table있는 url을 /dashboard 하위디렉토리에 넣고
/sessions/[:sessionId]로?

**Comment by easyandones** [comment]
> 후자에 s대신 어떤 단어를 넣는게 더 유저입장에서 편할 것 같아 아니면 기존 table있는 url을 /dashboard 하위디렉토리에 넣고 /sessions/[:sessionId]로?

세션 ID가 포함된 세션 내부 접속 url을 직접 하나하나 외워서 들어올 일은 거의 없기 때문에 짧은게 좋다고 봄.
특히 url을 복사해서 다른 곳에 공유하거나 할때도 짧은게 보기 좋다고 생각함.

**Comment by nayounsang** [comment]
사실 그건 루트페이지(홈페이지)말곤 다 똑같아서...짧은게 좋긴한데 그래도 기본적인 구분이나 파악은 돼야하지 않을까
일단 s로 하자

**Comment by easyandones** [comment]
> 사실 그건 루트페이지(홈페이지)말곤 다 똑같아서...짧은게 좋긴한데 그래도 기본적인 구분이나 파악은 돼야하지 않을까


나머지 대시보드 부분에서는 충분히 구분되게 잘 구현했다고 생각함.
그런데 저 세션 접속 url은 실제 외부에 많이 공유되고 직접 입력하거나 복사/붙여넣기해서 접속해야하는 주소임.

이 경우에는 특정 키워드를 넣으면서까지 url을 길게 만들기보다는 접근성이 좋도록 최대한 짧고 간결하게, 필수 요소만 담는게 좋다고 생각함.

**Comment by nayounsang** [comment]
그리고 드라이브에서 파일만 보는 뷰어 혹시 기능이 따로 없어?
그럼 그냥 s3링크만 열게해주면 되는거 아니야?
필기 보여주는건 세션 다시 들가서 보라고 기획했으니까
