### ISSUE TITLE
TOT: CI/CD에 대한 의견을 받습니다.

### ISSUE THREAD

**Issue by nayounsang** [Uni-class/catch-up-repo#353]
## 📝 개요
- ** 어차피 간단한 태스크임 편하게 ㄱㄱ **
#### 시간이 몇초 더 걸려도 yarn run prepare을 build전에 시작하자
- 이상하게 가끔씩 빌드가 실패함 이미 빌드 스크립트가 yarn run prepare && next build 인데도...
- Panda 메인테이너에게 말해봤으나 만족스런 대답을 듣지 못함 왜 그런거지?
#### build뿐만 아니라 프리티어, 린트 스크립트도 돌리자
- 근데 이거 고치려면 시간 좀 걸릴텐데?
## ✔️ To-Do
- [ ] 투두 내용 작성

**Comment by easyandones** [comment]
프론트
빌드 스크립트가 yarn run prepare && next build 인거면 이미 yarn run prepare를 build 전에 돌리는거 아니야?
무슨 차이인거야?

백
어차피 Prettier랑 ESLint는 개발환경에서 적용된 상태로 올라가지 않아?
애초에 개발 단계에서의 보조 툴이라 실제 코드 운영에는 별 상관없는데 이건 굳이?

**Comment by nayounsang** [comment]
> 프론트 빌드 스크립트가 yarn run prepare && next build 인거면 이미 yarn run prepare를 build 전에 돌리는거 아니야? 무슨 차이인거야?
- 맞음 내 상식상 그건데 모종의 이유로 BE PR에서 에러가 남
- 로그를 살펴보면 next build 과정 중 styled-system 폴더를 찾을 수 없다고 함 
- 애초에 step을 따로 빌드전에 빼서 prepare 스크립트 돌리면 에러가 안나더라?
> 백 어차피 Prettier랑 ESLint는 개발환경에서 적용된 상태로 올라가지 않아? 애초에 개발 단계에서의 보조 툴이라 실제 코드 운영에는 별 상관없는데 이건 굳이?
- 맞긴함
- 근데 돌리지는 않는 것 같던데

**Comment by easyandones** [comment]
근데 Prettier랑 ESLint를 굳이 빌드 서버에서 돌릴 이유가 있어?
코드 컴파일에 영향을 주진 않지 않나?

**Comment by 1000chw** [comment]
엉 빌드할 때는 굳이 필요 없지

**Comment by 1000chw** [comment]
빌드할 때 보단 push 할 때 eslint가 적용되어서 올라가는 로직이 있으면 좋긴 할듯? 엔터 쳐지는것도 코드 변경으로 들어가지고 하니까

**Comment by easyandones** [comment]
> * 맞음 내 상식상 그건데 모종의 이유로 BE PR에서 에러가 남
> * 로그를 살펴보면 next build 과정 중 styled-system 폴더를 찾을 수 없다고 함
> * 애초에 step을 따로 빌드전에 빼서 prepare 스크립트 돌리면 에러가 안나더라?

로컬에서는 동일하게 해도 멀쩡하고
빌드에서만 오류나는거면
빌드 환경에 문제가 있는 것 같은데 이건?

일부 패키지가 제대로 설치 안되었거나 환경이 달라서 버전이 꼬인건가

**Comment by nayounsang** [comment]
> > * 맞음 내 상식상 그건데 모종의 이유로 BE PR에서 에러가 남
> > * 로그를 살펴보면 next build 과정 중 styled-system 폴더를 찾을 수 없다고 함
> > * 애초에 step을 따로 빌드전에 빼서 prepare 스크립트 돌리면 에러가 안나더라?
> 
> 로컬에서는 동일하게 해도 멀쩡하고 빌드에서만 오류나는거면 빌드 환경에 문제가 있는 것 같은데 이건?
> 
> 일부 패키지가 제대로 설치 안되었거나 환경이 달라서 버전이 꼬인건가

근데 왜 될때가 있고 안될때가 있나?
이게 도저히 모르겠음
어차피 github action환경은 누가 개발하든 똑같잖아
보니까 나도 처음에 workflow개발할때만 몇번 그러고 이후엔 안나고
현우도 socket-server 개발했을때만 해당 에러가 발생함
https://github.com/chakra-ui/panda/discussions/2814
여기서도 유의미한 답을 찾을 수 없었네
