### ISSUE TITLE
FE: PDF a tag href target

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#448]
## 📝 개요
- PDF 내부 링크를 누를 경우 현재 페이지가 아니라 새 탭에서 열리도록 개선
- target: "_blank"

**Comment by nayounsang** [comment]
있으면 넘 좋을 것 같긴한데 가능한거야? react-pdf에서 제공해주나?

**Comment by nayounsang** [comment]
만약 pdf내 내부링크(다른 페이지로 이동)이 있으면 그건 _blank로 할 필요가 없을 것 같은데 구분돼있으려나?

**Comment by easyandones** [comment]
> 있으면 넘 좋을 것 같긴한데 가능한거야? react-pdf에서 제공해주나?

찾아봤는데 적용 가능한듯

**Comment by easyandones** [comment]
> 만약 pdf내 내부링크(다른 페이지로 이동)이 있으면 그건 _blank로 할 필요가 없을 것 같은데 구분돼있으려나?

별개로 관리되고 있어. 내부 링크는 아예 itemClickEventHandler를 따로 지정 가능
