### ISSUE TITLE
FE: dashboard 직접 접근 오류

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#477]
## 📝 개요
- Dashboard 개별 페이지를 지우는 것으로 합의되어 NavBar 표시 데이터 및 링크 등에서 빠졌으나 실제 경로상에서는 남아있기 때문에 url로 접속할 경우 페이지를 표시하는 도중 NavBar에서 현재 페이지에 대한 정보를 찾지 못해 오류가 발생하는 현상

## ✔️ To-Do
- [ ] 경로 상에서도 페이지를 삭제 (실제 dashboard의 page.tsx 및 dashboard 디렉토리 삭제)

## 예상 마감 기한
- [X] 우선순위가 낮아 고려 안함

**Comment by nayounsang** [comment]
임시적으로 /dashboard를 로그인화면 전 보고있는 페이지로 리다이렉트하는 역할만 하는 페이지로 해도 괜찮을듯
