### ISSUE TITLE
FE: Create Button Component

### ISSUE THREAD

**Issue by easyandones** [Uni-class/catch-up-repo#89]
## 📝 개요
- Button 컴포넌트 개발

## ✔️ To-Do
- [x] Button 컴포넌트 개발

**Comment by nayounsang** [comment]
어떤식으로 만들거임?
ui컴포넌트 참고하면 좋을거야
color: warn info success primary secondary 등등 (의미에 맞는 버튼)
variant: contained(배경색 채워진거) outlined(테두리랑 버튼텍스트만 색 적용) text(outlined에 테투리만없는거)
size: sm md lg
뭐 이런거 주면 더 쳬계적일듯

**Comment by easyandones** [comment]
> 어떤식으로 만들거임? ui컴포넌트 참고하면 좋을거야 color: warn info success primary secondary 등등 (의미에 맞는 버튼) variant: contained(배경색 채워진거) outlined(테두리랑 버튼텍스트만 색 적용) text(outlined에 테투리만없는거) size: sm md lg 뭐 이런거 주면 더 쳬계적일듯

사이즈나 컬러를 직접 제한하기보단 기본 틀 디자인만 잡아두고 세부적인건 직접 설정하도록 하는게 낫지 않으려나?
상황에 따라 다양한 형태로 변형할 경우가 많을텐데

**Comment by easyandones** [comment]
> > 어떤식으로 만들거임? ui컴포넌트 참고하면 좋을거야 color: warn info success primary secondary 등등 (의미에 맞는 버튼) variant: contained(배경색 채워진거) outlined(테두리랑 버튼텍스트만 색 적용) text(outlined에 테투리만없는거) size: sm md lg 뭐 이런거 주면 더 쳬계적일듯
> 
> 사이즈나 컬러를 직접 제한하기보단 기본 틀 디자인만 잡아두고 세부적인건 직접 설정하도록 하는게 낫지 않으려나? 상황에 따라 다양한 형태로 변형할 경우가 많을텐데

일단 기본 틀만 잡고 올린 다음에 이건 다음에 얘기 좀 해봐야할듯

**Comment by nayounsang** [comment]
그래도 어느정도 시스템화 하는게 중요하긴할듯
